### ISSUE TITLE
Receiving message that CRS is missing

### ISSUE THREAD

**Issue by cyyllam** [psrc/psrcelmer#1]
I installed the package via `devtools` on 12/8/22. And received an error message that CRS is missing. Removed the package and re-installed and updated dependent packages (including `sf`).

<img width="739" alt="image" src="https://user-images.githubusercontent.com/17414750/206550510-7a932490-7d22-4001-bcd7-6ae9e490d1f3.png">

**Comment by christopeak** [comment]
fixed in c07ee6d085b42f0a931dc78cf9c1ab660f4ef266
