### ISSUE TITLE
missing `magrittr` package?

### ISSUE THREAD

**Issue by cyyllam** [psrc/psrcelmer#4]
Re-installed package and ran reprex from documentation. Showing an error that it can't find the pipe. Should I also load `library(magrittr)` when using `relmer`?
<img width="596" alt="image" src="https://user-images.githubusercontent.com/17414750/206575938-44ffd00b-2ee2-42d8-ac35-465ea3172cdb.png">

**Comment by christopeak** [comment]
fixed in 1a76f00fdf60db29644e6acbd6ffa040e76e7fe0
